all:
	gcc Roman.c hw0401.c -o hw0401
	gcc hw0402-1.c hanoi.c -o hw0402-1
	gcc hw0402-2.c loop.c -o hw0402-2
	gcc hw0403.c factorial.c -o hw0403
	gcc hw0404.c resis.c -o hw0404
	gcc hw0405.c check.c -o hw0405
