All:
	gcc hw0601.c function.c -lm -o hw0601
	gcc hw0602.c function.c -lm -o hw0602
	gcc hw0603.c function.c -lm -o hw0603
	gcc hw0604.c function.c -lm -o hw0604
	gcc hw0605.c function.c -lm -o hw0605
